---
#
# Playbook to install the ELK stack + Beats
#
- name: install jel
  hosts: jel
  roles:
  - { role: ansible-role-java }
  - { role: ansible-role-elasticsearch }
  - { role: ansible-role-logstash }

- name: install kibana
  hosts: kibana
  roles:  
  - { role: ansible-role-kibana }

- name: install filebeat
  hosts: filebeat
  roles:
  - { role: ansible-role-filebeat }

