---
logstash_version: '7.x'

logstash_listen_port_beats: 5044

logstash_elasticsearch_hosts:
  - "192.168.16.17"
  - "192.168.16.3"
  - "192.168.16.4"

logstash_local_syslog_path: /var/log/syslog
logstash_monitor_local_syslog: true

logstash_dir: /usr/share/logstash

logstash_ssl_dir: /etc/pki/logstash
logstash_ssl_certificate_file: ""
logstash_ssl_key_file: ""

logstash_enabled_on_boot: true

logstash_install_plugins:
  - logstash-input-beats
  - logstash-filter-multiline
